import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from './_components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-full'>
          <div className="h-[80px] fixed inset-y-0 w-full z-[49]">
            <Navbar />
          </div>
          <main className="flex-1 pt-[80px] h-full container relative">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
